--- 
  page_url: "https://www.gailslabradoodles.com/current-litters"

  last_updated: 4/4/20

  last_known_text_hash: 3430a9cc01b4fe9748398853e407703600276cae

  keywords:
    - Luna
    - Turner
    - Mini

  alert_numbers:
    - ***REMOVED***
    - ***REMOVED***
