--- 
  page_url: "https://www.gailslabradoodles.com/current-litters"

  last_updated: 4/8/20

  last_known_text_hash: aee7c9da1eca538f691d8d7fefac9f973d9f583e

  keywords_sms:
    - Turner
    - Mini

  keywords_phone:
    - Luna

  sms_numbers:
    - "+***REMOVED***"
    - "+***REMOVED***"

  phone_numbers:
    - "+***REMOVED***"
