--- 
  page_url: "https://www.gailslabradoodles.com/current-litters"

  last_updated: 4/7/20

  last_known_text_hash: b09be7587c63d8aee3b510be2d7166064f94847c

  keywords_sms:
    - Turner
    - Mini

  keywords_phone:
    - Luna

  sms_numbers:
    - "+13234048016"
    - "+13234046924"

  phone_numbers:
    - "+13234046924"
