--- 
  page_url: "https://www.gailslabradoodles.com/current-litters"

  last_updated: 4/9/20

  last_known_text_hash: d71d54336bdd797aab8285fa1fb4ee2c053a731b

  keywords_sms:
    - Turner
    - Mini

  keywords_phone:
    - Luna

  sms_numbers:
    - "+***REMOVED***"
    - "+***REMOVED***"

  phone_numbers:
    - "+***REMOVED***"
