--- 
  page_url: "https://www.gailslabradoodles.com/current-litters"

  last_updated: 4/6/20

  last_known_text_hash: 165dc6c1a3e3c887b5deaad27011823d56b94b92

  keywords:
    - Luna
    - Turner
    - Mini

  alert_numbers:
    - "+13234048016"
