name: Deploy new-litter-detector to AWS Lambda
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  build_and_deploy_job:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_WORKSPACE/notifier/requirements.txt -t $GITHUB_WORKSPACE/notifier
    - name: Set environment
      id: set_env
      uses: mechtron/new-litter-detector/set-env-action@0.1.0
    - name: Run Terragrunt
      id: run_terragrunt
      uses: mechtron/new-litter-detector/terragrunt-action@phone-call-alerts
      with:
        env: ${{ steps.set_env.outputs.env }}
        tf_action: apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
    - name: Get the Terragrunt outputs
      run: |
        echo "The Lambda function's ARN is ${{ steps.run_terragrunt.outputs.function_arn }}"
        echo "The Lambda source hash is ${{ steps.run_terragrunt.outputs.source_code_hash }}"
        echo "The Lambda function's source last modified is ${{ steps.run_terragrunt.outputs.last_modified }}"
